apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: book-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev
    repoURL: https://github.com/izderadicka/person-service-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
