apiVersion: template.openshift.io/v1
kind: Template
name: service-template
metadata:
  name: service-template
  annotation:
    tags: java
    iconClass: icon-rh-openjdk
    openshift.io/display-name: The person service template
    description: This Template creates a new service
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}
      name:  ${APPLICATION_NAME}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: 8778-tcp
        port: 8778
        protocol: TCP
        targetPort: 8778
      selector:
        deployment:  ${APPLICATION_NAME}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: ${APPLICATION_NAME}
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            deployment: ${APPLICATION_NAME}
        spec:
          containers:
            - image: ${IMAGE_REF}
              imagePullPolicy: IfNotPresent
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              resources: {}
              env:
                - name: DB_HOST
                  value: postgresql.quarkus.svc.cluster.local
          restartPolicy: Always

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: 100
      wildcardPolicy: None

parameters:
  - name: APPLICATION_NAME
    description: Name of the application
    displayName: App name
    required: true
    value: new-person-service
  - name: IMAGE_REF
    description: Full image path
    displayName: Image
    required: true
    value: quay.io/izderadicka/person-service:v1.0.0