# permissions for end users to edit personservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: personservice-editor-role
rules:
- apiGroups:
  - charts.zderadicka.eu
  resources:
  - personservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.zderadicka.eu
  resources:
  - personservices/status
  verbs:
  - get
